export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_REGISTRATION_LOADING = "USER_REGISTRATION_LOADING";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE";

export const USER_ACCOUNT_LOADING = "USER_ACCOUNT_LOADING";
export const USER_ACCOUNT_CREATION = "USER_ACCOUNT_CREATION";
export const USER_ACCOUNT_CREATION_FAILURE = "USER_ACCOUNT_CREATION_FAILURE";
export const USER_ACCOUNT_RESET = "USER_ACCOUNT_RESET";

export const USER_ACCOUNT_UPDATE_LOADING = "USER_ACCOUNT_UPDATE_LOADING";
export const USER_ACCOUNT_UPDATE = "USER_ACCOUNT_UPDATE";
export const USER_ACCOUNT_UPDATE_FAILURE = "USER_ACCOUNT_UPDATE_FAILURE";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_ACCOUNT_DELETE = "USER_ACCOUNT_DELETE";
export const USER_ACCOUNT_DELETE_FAILURE = "USER_ACCOUNT_DELETE_FAILURE";

export const USER_ACCOUNT_UPDATE_PASSWORD_LOADING = "USER_ACCOUNT_UPDATE_PASSWORD_LOADING";
export const USER_ACCOUNT_UPDATE_PASSWORD = "USER_ACCOUNT_UPDATE_PASSWORD";
export const USER_ACCOUNT_UPDATE_PASSWORD_FAILURE = "USER_ACCOUNT_UPDATE_PASSWORD_FAILURE";

export const USER_ACCOUNT_LOGOUT = "USER_ACCOUNT_LOGOUT";

export const USER_FORGOT_PASSWORD_LOADING = "USER_FORGOT_PASSWORD_LOADING";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAILURE = "USER_FORGOT_PASSWORD_FAILURE";

export const USER_VERIFY_OTP_LOADING = "USER_VERIFY_OTP_LOADING";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAILURE = "USER_VERIFY_OTP_FAILURE";