export const GET_CART_MANAGEMENT_LOADING = "GET_CART_MANAGEMENT_LOADING";
export const GET_CART_MANAGEMENT_SUCCESS = "GET_CART_MANAGEMENT_SUCCESS";
export const GET_CART_MANAGEMENT_FAILURE = "GET_CART_MANAGEMENT_FAILURE";

export const ADD_CART_MANAGEMENT_LOADING = "ADD_CART_MANAGEMENT_LOADING";
export const ADD_CART_MANAGEMENT_SUCCESS = "ADD_CART_MANAGEMENT_SUCCESS";
export const ADD_CART_MANAGEMENT_FAILURE = "ADD_CART_MANAGEMENT_FAILURE";

export const REMOVE_CART_MANAGEMENT_LOADING = "REMOVE_CART_MANAGEMENT_LOADING";
export const REMOVE_CART_MANAGEMENT_SUCCESS = "REMOVE_CART_MANAGEMENT_SUCCESS";
export const REMOVE_CART_MANAGEMENT_FAILURE = "REMOVE_CART_MANAGEMENT_FAILURE";

export const UPDATE_CART_MANAGEMENT_LOADING = "UPDATE_CART_MANAGEMENT_LOADING";
export const UPDATE_CART_MANAGEMENT_SUCCESS = "UPDATE_CART_MANAGEMENT_SUCCESS";
export const UPDATE_CART_MANAGEMENT_FAILURE = "UPDATE_CART_MANAGEMENT_FAILURE";

export const DELETE_CART_MANAGEMENT_LOADING = "DELETE_CART_MANAGEMENT_LOADING";
export const DELETE_CART_MANAGEMENT_SUCCESS = "DELETE_CART_MANAGEMENT_SUCCESS";
export const DELETE_CART_MANAGEMENT_FAILURE = "DELETE_CART_MANAGEMENT_FAILURE";

export const PLACE_ORDER_LOADING = "PLACE_ORDER_LOADING";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILURE = "PLACE_ORDER_FAILURE";

export const LOCAL_CART_MANAGEMENT = "LOCAL_CART_MANAGEMENT";
export const LOCAL_CART_RESET = "LOCAL_CART_RESET";
export const LOCAL_ADDRESS_MANAGEMENT = "LOCAL_ADDRESS_MANAGEMENT";