export const DATA = [
  {
    id: 1,
    title: 'Title here 1',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 2,
    title: 'Title here 2',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 3,
    title: 'Title here 3',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 4,
    title: 'Title here 4',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 6,
    title: 'Title here 6',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 7,
    title: 'Title here 7',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  {
    id: 8,
    title: 'Title here 8',
    classification: 'Men',
    cat: 'Footwear',
    date: '12th feb 2022',
    uri: 'https://wallpaperaccess.com/full/317501.jpg',
  },
  
];
