export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";

export const POST_PRODUCTS_LOADING = "POST_PRODUCTS_LOADING";
export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_FAILURE = "POST_PRODUCTS_FAILURE";
export const POST_PRODUCTS_RESET = "POST_PRODUCTS_RESET";

export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
export const GET_PRODUCT_RESET = "GET_PRODUCT_RESET";

export const DELETE_PRODUCT_LOADING = "DELETE_PRODUCT_LOADING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const PRODUCT_UPDATE_LOADING = "PRODUCT_UPDATE_LOADING";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";

export const MULTI_PRODUCT_ADD_LOADING = "MULTI_PRODUCT_ADD_LOADING";
export const MULTI_PRODUCT_ADD_SUCCESS = "MULTI_PRODUCT_ADD_SUCCESS";
export const MULTI_PRODUCT_ADD_FAILURE = "MULTI_PRODUCT_ADD_FAILURE";

export const FILE_UPLOAD_LOADING = "FILE_UPLOAD_LOADING";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";

export const STORE_PRODUCT_GET_LOADING = "STORE_PRODUCT_GET_LOADING";
export const STORE_PRODUCT_GET_SUCCESS = "STORE_PRODUCT_GET_SUCCESS";
export const STORE_PRODUCT_GET_FAILURE = "STORE_PRODUCT_GET_FAILURE";