export const GET_ALL_STORE_LOADING = "GET_ALL_STORE_LOADING";
export const GET_ALL_STORE_SUCCESS = "GET_ALL_STORE_SUCCESS";
export const GET_ALL_STORE_FAILURE = "GET_ALL_STORE_FAILURE";

export const POST_STORE_LOADING = "POST_STORE_LOADING";
export const POST_STORE_SUCCESS = "POST_STORE_SUCCESS";
export const POST_STORE_FAILURE = "POST_STORE_FAILURE";
